variables:

  categories:
    - name: Core
      scategories:
        - name: Time
          crate: chrono
          c_url: https://crates.io/crates/chrono
        - name: Static Global Variables
          crate: lazy_static
          c_url: https://crates.io/crates/lazy_static
        - name: Data Parallelism
          crate: rayon
          c_url: https://crates.io/crates/rayon
          comment: This sub category possibly needs to be included in another category alltogether.
        - name: Concurrency
        - name: Asynchrony
          crate: futures
          c_url: https://crates.io/crates/futures
        - name: Parallelism
    - name: Rust
      scategories:
        - name: Cargo Outdated
          crate: cargo-outdated
          c_url: https://crates.io/crates/cargo-outdated
        - name: Cargo Watch
          crate: cargo-watch
          c_url: https://crates.io/crates/cargo-watch
        - name: Formatting Consistency
          crate: rustfmt
          c_url: https://crates.io/crates/rustfmt
        - name: Linter
          crate: clippy
          c_url: https://crates.io/crates/clippy
    - name: Essentials
      scategories:
        - name: Logging
          crate: log
          c_url: https://crates.io/crates/log
        - name: Structured Logging
          crate: slog
          c_url: https://crates.io/crates/slog
        - name: Log File Appenders
        - name: Regex
          crate: regex
          c_url: https://crates.io/crates/regex
        - name: Temporary File Handling
          crate: tempfile
          c_url: https://crates.io/crates/tempfile
        - name: Random Numbers
          crate: rand
          c_url: https://crates.io/crates/rand
        - name: Semver
          crate: semver
          c_url: https://crates.io/crates/semver
        - name: IO
        - name: Scheduling/Timer/cron
    - name: Network Essentials
      scategories:
        - name: URL Handling
          crate: url
          c_url: https://crates.io/crates/url
        - name: HTTP Client
          crate: reqwest
          c_url: https://crates.io/crates/reqwest
        - name: Bit handling
        - name: Non-blocking IO
          crate: tokio-core
          c_url: https://crates.io/crates/tokio-core
    - name: Network
      scategories:
        - name: Protocols
        - name: Servers
        - name: RPC
    - name: Security Essentials
      scategories:
        - name: SSL/TLS
          crate: native-tls
          c_url: https://crates.io/crates/native-tls
        - name: Cryptography
          crate: ring
          c_url: https://crates.io/crates/ring
        - name: Authentication
    - name: Serialization and Deserialization
      scategories:
        - name: Command Line Parsing
          crate: clap
          c_url: https://crates.io/crates/clap
        - name: Command Line Parsing
          crate: docopt
          c_url: https://crates.io/crates/docopt
          alt: True
        - name: TOML
        - name: JSON
          crate: serde_json
          c_url: https://crates.io/crates/serde_json
        - name: YAML
          crate: serde_yaml
          c_url: https://crates.io/crates/serde_yaml
        - name: CSV
          crate: csv
          c_url: https://crates.io/crates/csv
        - name: xml
        - name: mime
        - name: Parser Generators
    - name: Common
      scategories:
        - name: Platform Bindings
        - name: Process Management
        - name: Memory Management
        - name: File and directory handling
        - name: Functional Programming and Control Flow
        - name: Compression
        - name: Web Frameworks
        - name: Template Engines
    - name: Database
      scategories:
        - name: Database Connection Pooling
          crate: r2d2
          c_url: https://crates.io/crates/r2d2
        - name: ORM
          crate: diesel
          c_url: https://crates.io/crates/diesel
        - name: MySQL
        - name: Postgresql
          crate: postgres
          c_url: https://crates.io/crates/postgres
        - name: Elasticsearch
          crate: elastic
          c_url: https://crates.io/crates/elastic
    - name: HPC and Data Science
      scategories:
        - name: Machine Learning
        - name: Scientific Computing
        - name: Data Structures
        - name: Math
        - name: Statistics
    - name: Application Essentials
      scategories:
        - name: Terminal
          crate: termion
          c_url: https://crates.io/crates/termion
        - name: Image libraries
          crate: image
          c_url: https://crates.io/crates/image
        - name: GUI
        - name: OpenGL
        - name: Sound
    - name: Testing
      scategories:
        - name: Unit Testing
        - name: Test Frameworks
        - name: Integration Testing
        - name: Mocking

  panel:
    - name: Stephan Buys
      bio: Instigator
      profile:
      shortcut:
      company:
        name: Panoptix
    - name: Eric Kidd
      bio: Instigator
      profile:
      shortcut:

  company:
    - name: Panoptix
      about: A small company in ZA

templates:
  - src: LIST.md.jinja2
    dst: ../README.md
  - src: PANEL.md.jinja2
    dst: ../PANEL.md
  - src: PROJECTS.md.jinja2
    dst: ../PROJECTS.md
